### ISSUE TITLE
Name change tool unlikely to actually help

### ISSUE THREAD

**Issue by TJC** [kimburgess/censusfail#3]
A lot of govt records are stored in ASCII format, not Unicode.

If the eCensus forms even let you enter Unicode, then I strongly suspect it will be down-converted back to ASCII pretty quickly, before it's used to compare with other govt records. Have you considered that your advice may be misleading about its effectiveness?

**Comment by kimburgess** [comment]
Yep, you're absolutely correct. I was hedging my bets that they'd allow unicode input for names. I was wrong - looking at their site tonight the front-end validation filters from alphanumeric only.
