### ISSUE TITLE
This isn't necessary

### ISSUE THREAD

**Issue by iZiMO** [kimburgess/censusfail#4]
They're using a salt. Without the salt (which is discarded after hashing) you can't recreate the hash. Name and address, etc isn't enough.

**Comment by iZiMO** [comment]
Whoops, correction, it's not discarded. Still, you can't recreate the hash without the salt

**Comment by kimburgess** [comment]
Not sure what the issue this is referring to is? Regardless, from some more diving today it looks like they way this info is being stored / linked is a little different. Site has been updated to remove reference hashing as it's no longer relevant.
